#!/usr/bin/env zsh

#  \
#  \\,
#   \\\,^,.,,.                    “Zero to Hero”
#   ,;7~((\))`;;,,               <zerotohero.dev>
#   ,(@') ;)`))\;;',    stay up to date, be curious: learn
#    )  . ),((  ))\;,
#   /;`,,/7),)) )) )\,,
#  (& )`   (,((,((;( ))\,

TAG="0.0.10"

# shellcheck disable=SC1090
source ~/.zprofile

docker run -e FIZZ_DEPLOYMENT_TYPE="$FIZZ_DEPLOYMENT_TYPE" \
-e FIZZ_STORE_SVC_PORT="$FIZZ_STORE_SVC_PORT" \
-e FIZZ_STORE_HONEYBADGER_API_KEY="$FIZZ_STORE_HONEYBADGER_API_KEY" \
-e FIZZ_STORE_CRYPTO_ENDPOINT_URL="$FIZZ_STORE_CRYPTO_ENDPOINT_URL" \
-e FIZZ_STORE_IDM_ENDPOINT_URL="$FIZZ_STORE_IDM_ENDPOINT_URL" \
-e FIZZ_STORE_USERS_TABLE_NAME="$FIZZ_STORE_USERS_TABLE_NAME" \
-e FIZZ_STORE_PLANS_TABLE_NAME="$FIZZ_STORE_PLANS_TABLE_NAME" \
-e FIZZ_STORE_STRIPE_PRIVATE_KEY="$FIZZ_STORE_STRIPE_PRIVATE_KEY" \
-e FIZZ_STORE_STRIPE_PUBLIC_KEY="$FIZZ_STORE_STRIPE_PUBLIC_KEY" \
-e FIZZ_STORE_SUBSCRIBE_API_URL="$FIZZ_STORE_SUBSCRIBE_API_URL" \
-e FIZZ_STORE_SUBSCRIBE_SUCCESS_URL="$FIZZ_STORE_SUBSCRIBE_SUCCESS_URL" \
-e FIZZ_STORE_SUBSCRIBE_ERROR_URL="$FIZZ_STORE_SUBSCRIBE_ERROR_URL" \
-e FIZZ_LOG_DESTINATION="$FIZZ_LOG_DESTINATION" \
zerotohero-dev/fizz-store:$TAG
